language: python
sudo: false
matrix:
    include:
    - python: "3.4"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"
    - python: "3.3"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"
    - python: "2.7"
      env: DEPS="numpy scipy nose matplotlib pytables cython beautiful-soup pandas"

addons:
    apt:
        packages:
        - libgsl0-dev
        - libgsl0ldbl

install: 
    - wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda${TRAVIS_PYTHON_VERSION:0:1}/bin:$PATH
    # See: https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
    - conda update --yes --no-deps conda
    - conda config --set always_yes yes --set changeps1 no
    # Learned the hard way: miniconda is not always up-to-date with conda.
    - conda update --yes conda
    - conda install --yes -c conda conda-env
    - conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
    - pip install coveralls 
    - git clone https://github.com/rth/opacplot2 --branch=master --single-branch
    - cd opacplot2/
# so we can use the cythoned files without installing them
    - python setup.py install
    - python setup.py build_ext --inplace -f -v # this is 
    - cd ..
    - rm -rf opacplot2/
    - python setup.py install
    - cd ~/
    - pwd
#- ls -R

# command to run tests
script: 
    - python  -c "import hedp.tests; hedp.tests.test(coverage=True)"

#    - coverage run --source=hedp ./hedp/tests/run.py

#after_success:
#    coveralls

